### ISSUE TITLE
Sitedorks queries not workin in Kali Linux

### ISSUE THREAD

**Issue by Dorado811** [Zarcolio/sitedorks#4] opened 2023-04-21 23:34 UTC
I tried sitedorks examples on kali linux 6.1.0-kali7-amd64 and none of them work.  

Here is what I get:
┌──(root㉿kali)-[~]
└─# sitedorks -query '"uber website"'  
Not providing -cat can open a whole lot of tabs/windows in your browser. Do you want to continue? (y/n) y
Traceback (most recent call last):
  File "/usr/local/bin/sitedorks", line 288, in <module>
    dQuery[iUrls] += sEndQuery
    ~~~~~~^^^^^^^
KeyError: 39

Thanks in advanced:
Willie Hernandez.

**Comment by Zarcolio** [comment] 2023-04-22 09:17
Hi Willie, 

I could not reproduce the error but I've tried to implement a fix.
Can you try with the version you have, if you also get this error if you use for example: -cat cloud 
Please try the new version too.

Also, I've added an option to use a different browser :)

**Comment by Zarcolio** [comment] 2023-04-28 07:07
Closing the issue, no reply after 1 week.
Hope I fixed it.

**Closed as not planned** 2023-04-28 07:06 UTC
